name: Validate Docs and Cursor Rules

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run PyMarkdown scan
        run: |
          pymarkdown scan . || true
      - name: Validate Cursor rules (strict)
        run: |
          mkdir -p artifacts
          python3 scripts/validate_cursor_rules.py --strict --report-json artifacts/cursor_rules_report.json .cursor/rules prompts/generate_cursor_rules.prompt.md
      - name: Upload validator report
        uses: actions/upload-artifact@v4
        with:
          name: cursor-rules-report
          path: artifacts/cursor_rules_report.json
